/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nakliye;

/**
 *
 * @author Ozardali
 */
public class a_index extends javax.swing.JFrame {

    /**
     * Creates new form a_index
     */
    public a_index() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        aracbtn = new javax.swing.JButton();
        musteribtn = new javax.swing.JButton();
        soforbtn = new javax.swing.JButton();
        nakliyekayitbtn = new javax.swing.JButton();
        ayarbtn = new javax.swing.JButton();
        raporbtn = new javax.swing.JButton();
        messagebtn = new javax.swing.JButton();
        messagebtn1 = new javax.swing.JButton();
        odemeler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Yönetim Sistemi Anasayfa");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel3.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("YÖNETİM ALANI");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addContainerGap())
        );

        aracbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        aracbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nakliye/iconpack/64/truck.png"))); // NOI18N
        aracbtn.setText("ARAÇLAR");
        aracbtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        aracbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aracbtnActionPerformed(evt);
            }
        });

        musteribtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        musteribtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nakliye/iconpack/64/users.png"))); // NOI18N
        musteribtn.setText("MÜŞTERİLER");
        musteribtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        musteribtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musteribtnActionPerformed(evt);
            }
        });

        soforbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        soforbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nakliye/iconpack/64/Man.png"))); // NOI18N
        soforbtn.setText("ŞOFÖRLER");
        soforbtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        soforbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soforbtnActionPerformed(evt);
            }
        });

        nakliyekayitbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nakliyekayitbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nakliye/iconpack/64/add.png"))); // NOI18N
        nakliyekayitbtn.setText("YENİ NAKLİYE KAYIT");
        nakliyekayitbtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        nakliyekayitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nakliyekayitbtnActionPerformed(evt);
            }
        });

        ayarbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ayarbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nakliye/iconpack/64/Web-management.png"))); // NOI18N
        ayarbtn.setText("İŞLEM AYARLARI");
        ayarbtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ayarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayarbtnActionPerformed(evt);
            }
        });

        raporbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        raporbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nakliye/iconpack/64/Reports.png"))); // NOI18N
        raporbtn.setText("RAPORLAR");
        raporbtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        raporbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raporbtnActionPerformed(evt);
            }
        });

        messagebtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        messagebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nakliye/iconpack/64/Message-already-read.png"))); // NOI18N
        messagebtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        messagebtn.setLabel("MESAJLAR");
        messagebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messagebtnActionPerformed(evt);
            }
        });

        messagebtn1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        messagebtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nakliye/iconpack/64/information.png"))); // NOI18N
        messagebtn1.setText("HAKKINDA");
        messagebtn1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        messagebtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messagebtn1ActionPerformed(evt);
            }
        });

        odemeler.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        odemeler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nakliye/iconpack/64/add.png"))); // NOI18N
        odemeler.setText("ÖDEME");
        odemeler.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        odemeler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odemelerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(musteribtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ayarbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(odemeler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(soforbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(raporbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nakliyekayitbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(messagebtn, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                            .addComponent(messagebtn1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(aracbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aracbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(musteribtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soforbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nakliyekayitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(messagebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(odemeler, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(raporbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ayarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(messagebtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void soforbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soforbtnActionPerformed
         a_drivers a_driver = new a_drivers();
        this.setVisible(false);
          a_driver.setVisible(true); 
    }//GEN-LAST:event_soforbtnActionPerformed

    private void nakliyekayitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nakliyekayitbtnActionPerformed
        a_cargoadd a_cargoadd = new a_cargoadd();
    
          a_cargoadd.setVisible(true);
    }//GEN-LAST:event_nakliyekayitbtnActionPerformed

    private void raporbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raporbtnActionPerformed
         a_report a_report = new a_report();
       this.setVisible(false);
          a_report.setVisible(true); 
    }//GEN-LAST:event_raporbtnActionPerformed

    private void musteribtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musteribtnActionPerformed
     
          a_client a_client = new a_client();
        this.setVisible(false);
          a_client.setVisible(true); 
    }//GEN-LAST:event_musteribtnActionPerformed

    private void aracbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aracbtnActionPerformed
      a_truck a_truck = new a_truck();
      this.setVisible(false);
          a_truck.setVisible(true); 
    }//GEN-LAST:event_aracbtnActionPerformed

    private void ayarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayarbtnActionPerformed
        a_settings a_settings = new a_settings();
    this.setVisible(false);
          a_settings.setVisible(true);
    }//GEN-LAST:event_ayarbtnActionPerformed

    private void messagebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messagebtnActionPerformed
 a_message a_message = new a_message();
   
          a_message.setVisible(true);    }//GEN-LAST:event_messagebtnActionPerformed

    private void messagebtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messagebtn1ActionPerformed
a_info a_info = new a_info();
   
          a_info.setVisible(true);   
    }//GEN-LAST:event_messagebtn1ActionPerformed

    private void odemelerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odemelerActionPerformed
     a_odemeler a_odemeler = new a_odemeler();
        this.setVisible(false);
          a_odemeler.setVisible(true); 
    }//GEN-LAST:event_odemelerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(a_index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(a_index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(a_index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(a_index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new a_index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aracbtn;
    private javax.swing.JButton ayarbtn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton messagebtn;
    private javax.swing.JButton messagebtn1;
    private javax.swing.JButton musteribtn;
    private javax.swing.JButton nakliyekayitbtn;
    private javax.swing.JButton odemeler;
    private javax.swing.JButton raporbtn;
    private javax.swing.JButton soforbtn;
    // End of variables declaration//GEN-END:variables
}
