/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nakliye;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import static nakliye.nakliyeBaglanti.ConnectDb;
import static nakliye.u_login.musteri;

/**
 *
 * @author Ozardali
 */
public class u_index extends javax.swing.JFrame {

    Connection conn=null;
    ResultSet re=null;
    PreparedStatement pst=null;
    /**
     * Creates new form a_index
     */
    public u_index() {
        initComponents();
                  conn=ConnectDb();
                    try{ 
            String sql="Select musteri_adsoyad from musteriler where musteri_id="+musteri;
            pst=conn.prepareStatement(sql);
            re=(ResultSet) pst.executeQuery();
            
            if(re.next()){
                String ekle1=re.getString("musteri_adsoyad");
                musteri_id.setText(ekle1);
                  }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
                  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        musteri_id = new javax.swing.JLabel();
        musteri_id1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        musteribtn = new javax.swing.JButton();
        nakliyekayitbtn = new javax.swing.JButton();
        dosyayzdr = new javax.swing.JButton();
        raporbtn = new javax.swing.JButton();
        odemebildirbtn = new javax.swing.JButton();
        mesajlarbtn = new javax.swing.JButton();
        nakliyelerbtn = new javax.swing.JButton();
        bilgibtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Yönetim Sistemi Anasayfa");
        setPreferredSize(new java.awt.Dimension(706, 400));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel3.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("KULLANICI ALANI");

        musteri_id.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        musteri_id.setForeground(new java.awt.Color(255, 255, 255));
        musteri_id.setText("İsim Soyisim");

        musteri_id1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        musteri_id1.setForeground(new java.awt.Color(255, 255, 255));
        musteri_id1.setText("Sayın:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(musteri_id1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(musteri_id)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(musteri_id)
                    .addComponent(musteri_id1))
                .addContainerGap())
        );

        musteribtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        musteribtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nakliye/iconpack/64/users.png"))); // NOI18N
        musteribtn.setText("PROFİLİM");
        musteribtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        musteribtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        musteribtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musteribtnActionPerformed(evt);
            }
        });

        nakliyekayitbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nakliyekayitbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nakliye/iconpack/64/map.png"))); // NOI18N
        nakliyekayitbtn.setText("YENİ NAKLİYE");
        nakliyekayitbtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        nakliyekayitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nakliyekayitbtnActionPerformed(evt);
            }
        });

        dosyayzdr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dosyayzdr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nakliye/iconpack/64/File-explorer.png"))); // NOI18N
        dosyayzdr.setText("DOSYA İŞLEM");
        dosyayzdr.setToolTipText("");
        dosyayzdr.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        dosyayzdr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosyayzdrActionPerformed(evt);
            }
        });

        raporbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        raporbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nakliye/iconpack/64/Reports.png"))); // NOI18N
        raporbtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        raporbtn.setLabel("RAPORLAMA");
        raporbtn.setMaximumSize(new java.awt.Dimension(165, 73));
        raporbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raporbtnActionPerformed(evt);
            }
        });

        odemebildirbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        odemebildirbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nakliye/iconpack/64/add.png"))); // NOI18N
        odemebildirbtn.setText("ÖDEME İŞLEMLERİ");
        odemebildirbtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        odemebildirbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odemebildirbtnActionPerformed(evt);
            }
        });

        mesajlarbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mesajlarbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nakliye/iconpack/64/Message-already-read.png"))); // NOI18N
        mesajlarbtn.setText("MESAJLAR");
        mesajlarbtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        mesajlarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesajlarbtnActionPerformed(evt);
            }
        });

        nakliyelerbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nakliyelerbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nakliye/iconpack/64/Order-history.png"))); // NOI18N
        nakliyelerbtn.setText("NAKLİYELERİM");
        nakliyelerbtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        nakliyelerbtn.setMaximumSize(new java.awt.Dimension(195, 73));
        nakliyelerbtn.setMinimumSize(new java.awt.Dimension(195, 73));
        nakliyelerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nakliyelerbtnActionPerformed(evt);
            }
        });

        bilgibtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bilgibtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nakliye/iconpack/64/information.png"))); // NOI18N
        bilgibtn.setText("SİSTEM BİLGİSİ");
        bilgibtn.setToolTipText("");
        bilgibtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bilgibtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilgibtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(musteribtn, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(nakliyelerbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(bilgibtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nakliyekayitbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(odemebildirbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dosyayzdr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mesajlarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(raporbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(musteribtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nakliyekayitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(raporbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(odemebildirbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesajlarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nakliyelerbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dosyayzdr, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bilgibtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nakliyekayitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nakliyekayitbtnActionPerformed
         u_cargoadd u_cargoadd = new u_cargoadd();
          u_cargoadd.setVisible(true); 
    }//GEN-LAST:event_nakliyekayitbtnActionPerformed

    private void raporbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raporbtnActionPerformed
         u_report u_report = new u_report();
          u_report.setVisible(true); 
    }//GEN-LAST:event_raporbtnActionPerformed

    private void musteribtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musteribtnActionPerformed
     
          u_profile u_profile = new u_profile();
          u_profile.setVisible(true); 
    }//GEN-LAST:event_musteribtnActionPerformed

    private void dosyayzdrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosyayzdrActionPerformed
        u_form u_form = new u_form();
          u_form.setVisible(true); 
        // TODO add your handling code here:
    }//GEN-LAST:event_dosyayzdrActionPerformed

    private void odemebildirbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odemebildirbtnActionPerformed
         u_odemebildir u_odemebildir = new u_odemebildir();
          u_odemebildir.setVisible(true); 
    }//GEN-LAST:event_odemebildirbtnActionPerformed

    private void mesajlarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesajlarbtnActionPerformed
 u_mesajlar u_mesajlar = new u_mesajlar();
          u_mesajlar.setVisible(true);     }//GEN-LAST:event_mesajlarbtnActionPerformed

    private void nakliyelerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nakliyelerbtnActionPerformed
u_nakliyelerim u_nakliyelerim = new u_nakliyelerim();
          u_nakliyelerim.setVisible(true);     
        // TODO add your handling code here:
    }//GEN-LAST:event_nakliyelerbtnActionPerformed

    private void bilgibtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilgibtnActionPerformed
  a_info a_info = new a_info();
          a_info.setVisible(true);  
        // TODO add your handling code here:
    }//GEN-LAST:event_bilgibtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(u_index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(u_index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(u_index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(u_index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new u_index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bilgibtn;
    private javax.swing.JButton dosyayzdr;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton mesajlarbtn;
    private javax.swing.JLabel musteri_id;
    private javax.swing.JLabel musteri_id1;
    private javax.swing.JButton musteribtn;
    private javax.swing.JButton nakliyekayitbtn;
    private javax.swing.JButton nakliyelerbtn;
    private javax.swing.JButton odemebildirbtn;
    private javax.swing.JButton raporbtn;
    // End of variables declaration//GEN-END:variables
}
